= java-code-chunker

Python library that chunks Java packages, methods, and variables into a Python list consisting of a number of Python dictionaries. This list of dictionaries can then be used for vector-store creation, which can provide granular context for OpenAI queries.

== Contributing

The GitHub repository for this package is https://github.com/break-free/java-code-chunker.

The `main` branch is protected therefore any contributions require a branch to be created. Branch names should be preprended with either `feature_` or `fix_` to indicate whether new functionality or a refactor/fix is being made (e.g, `fix_update-readme`. Once the branch is complete, it can be merged back into `main`.

The repository includes additional directories, such as `setup`, `info`, and `training`, and files, such as `main.py`, that includes additional resources for development and usage examples.

== Packaging

This Python package was produced using https://hatch.pypa.io/latest/config/build/[hatchling]. Refer to the `pyproject.toml` for specifics.

== Notes

This code has been battle-tested with *one* application. If you encounter any issues then please https://github.com/break-free/java-code-chunker/issues[submit an issue ticket here on GitHub].
